test

diff --git a/.github/workflows/ci_cd.yml b/.github/workflows/ci_cd.yml
--- a/.github/workflows/ci_cd.yml
+++ b/.github/workflows/ci_cd.yml
@@ -43,6 +43,7 @@
 #                           an openremote submodule).
 # - CLEAN_INSTALL         - Should the .ci_cd/host_init/clean.sh script be run during deployment (warning this will delete
 #                           assets, rules, etc.)
+# - PUSH_SNAPSHOT         - Should a SNAPSHOT docker image be pushed to AWS ECR
 # - COMMIT                - Which branch/SHA should be checked out for the deployment (defaults to trigger commit)
 # - OR_HOSTNAME           - FQDN of host to deploy to (e.g. demo.openremote.app)
 # - SSH_USER              - Set/override the SSH user to use for SSH/SCP commands
@@ -74,6 +75,9 @@ on:
         description: 'Manager docker tag to pull'
       CLEAN_INSTALL:
         description: 'Delete data before starting'
+        type: boolean
+      PUSH_SNAPSHOT:
+        description: 'Push SNAPSHOT docker image to ECR'
         type: boolean
       COMMIT:
         description: 'Repo branch or commit SHA to checkout'
@@ -163,9 +167,20 @@ jobs:
         id: ip-address
         shell: bash
         run: |
-          set -e
-          PUBLIC_IPV4=$(curl -sf v4.ident.me 2>/dev/null || true)
-          PUBLIC_IPV6=$(curl -sf v6.ident.me 2>/dev/null || true)
+          OPTS="-sf -m 5"
+          
+          # Try Primary v4 -> Fallback v4 -> Default to empty
+          PUBLIC_IPV4=$(curl $OPTS v4.ident.me || curl $OPTS 4.tnedi.me || true)
+          
+          # Try Primary v6 -> Fallback v6 -> Default to empty
+          PUBLIC_IPV6=$(curl $OPTS v6.ident.me || curl $OPTS 6.tnedi.me || true)
+          
+          # Validation: Ensure at least one IP was found
+          if [[ -z "$PUBLIC_IPV4" && -z "$PUBLIC_IPV6" ]]; then
+          echo "::error::Could not determine Public IP (both v4 and v6 failed)."
+          exit 1
+          fi
+          
           echo "ipv4=$PUBLIC_IPV4" >> $GITHUB_OUTPUT
           echo "ipv6=$PUBLIC_IPV6" >> $GITHUB_OUTPUT
 
@@ -176,6 +191,7 @@ jobs:
           ref: ${{ steps.inputs-and-secrets.outputs.COMMIT }}
           submodules: recursive
           fetch-depth: 200
+          lfs: 'true'
 
       # Check which files have changed to only run appropriate tests and checks
       - name: Backend files changed
@@ -249,6 +265,14 @@ jobs:
             profile
           sparse-checkout-cone-mode: false
 
+      - name: Install node_modules
+        if: steps.ui-files-changed.outputs.any_modified == 'true'
+        run: yarn --immutable
+
+      - name: Check UI dependencies
+        if: steps.ui-files-changed.outputs.any_modified == 'true' && steps.is_main_repo.outputs.value == 'true'
+        run: npx knip@5.88.0 -c ui/knip.jsonc
+
       - name: Check deployment build.gradle
         id: check_deployment_gradle
         uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3
@@ -266,6 +290,14 @@ jobs:
         uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6 # v3
         with:
           files: ".ci_cd/ci_cd.json"
+
+      - name: Set up JDK 21 and gradle cache
+        id: java
+        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
+        with:
+          distribution: 'temurin'
+          java-version: '21'
+          cache: 'gradle'
 
       - name: Get version details
         id: get-version-details
@@ -293,6 +325,7 @@ jobs:
           eventName = os.getenv('GITHUB_EVENT_NAME')
           refName = os.getenv('GITHUB_REF_NAME')
           refType = os.getenv('GITHUB_REF_TYPE')
+          repoOwner = os.getenv('GITHUB_REPOSITORY_OWNER')
           isMainRepo = os.getenv('IS_MAIN_REPO') == 'true'
           isRelease = os.getenv('IS_RELEASE') == 'true'
           managerVersion = os.getenv('MANAGER_VERSION')
@@ -340,20 +373,21 @@ jobs:
               os.system(f"echo 'firstDockerTag={firstDockerTag}' >> $GITHUB_OUTPUT")
               os.system(f" echo 'Manager tags to push to docker hub: {dockerPublishTags}'")
               dockerPublishTags = " ".join(map(lambda t: f"-t openremote/manager:{t.strip()}", dockerPublishTags.split(",")))
-              os.system(f"echo 'dockerTags={dockerPublishTags}' >> $GITHUB_OUTPUT")
+              if repoOwner == 'openremote':
+                os.system(f"echo 'dockerTags={dockerPublishTags}' >> $GITHUB_OUTPUT")
 
-            if mavenPublishTag is not None:
+            if mavenPublishTag is not None and repoOwner == 'openremote':
               mavenPublishTag = mavenPublishTag.replace("$version", version)
               os.system(f" echo 'Maven publish version: {mavenPublishTag}'")
               os.system(f"echo 'mavenTag={mavenPublishTag}' >> $GITHUB_OUTPUT")
 
-            if npmPublishTag is not None:
+            if npmPublishTag is not None and repoOwner == 'openremote':
               npmPublishTag = npmPublishTag.replace("$version", version)
               os.system(f" echo 'npm publish version: {npmPublishTag}'")
               os.system(f"echo 'npmTag={npmPublishTag}' >> $GITHUB_OUTPUT")
 
           deployStr = None
-          if deploys is not None:
+          if deploys is not None and repoOwner == 'openremote':
             if not isinstance(deploys, list):
               deploys = [deploys]
 
@@ -396,7 +430,9 @@ jobs:
         shell: python
         run: |
           import os
+          import sys
 
+          repoOwner = os.getenv('GITHUB_REPOSITORY_OWNER')
           isMainRepo = os.getenv('IS_MAIN_REPO') == 'true'
           deployments = os.getenv('DEPLOYMENTS')
           eventName = os.getenv('GITHUB_EVENT_NAME')
@@ -405,7 +441,7 @@ jobs:
           inputEnv = os.getenv('INPUT_ENVIRONMENT')
           managerVersion = os.getenv('MANAGER_VERSION')
 
-          if eventName == 'workflow_dispatch' and refType != 'tag':
+          if eventName == 'workflow_dispatch' and refType != 'tag' and repoOwner == 'openremote':
             if isMainRepo:
               tag=inputTag
               if not inputTag:
@@ -416,16 +452,23 @@ jobs:
 
           if not isMainRepo:
             if "-SNAPSHOT" in deployments:
-              os.system("SNAPSHOT manager docker images not currently supported for custom project deployment")
+              os.system("echo 'SNAPSHOT manager docker images not currently supported for custom project deployment'")
               sys.exit(1)
-
           os.system(f"echo 'value={deployments}' >> $GITHUB_OUTPUT")
+
+          pushSnapshot = os.getenv('INPUT_PUSH_SNAPSHOT')
+          if pushSnapshot == 'true' and repoOwner != 'openremote':
+            os.system("echo 'Only Openremote organisation can push to ECR'")
+            sys.exit(1)
+          else:
+            os.system(f"echo 'pushSnapshot={pushSnapshot}' >> $GITHUB_OUTPUT")
         env:
           IS_MAIN_REPO: ${{ steps.is_main_repo.outputs.value }}
           MANAGER_VERSION: ${{ steps.is_main_repo.outputs.ref }}
           DEPLOYMENTS: ${{ steps.ci-cd-output.outputs.deploys }}
           INPUT_ENVIRONMENT: ${{ steps.inputs-and-secrets.outputs.ENVIRONMENT }}
           INPUT_MANAGER_TAG: ${{steps.inputs-and-secrets.outputs.MANAGER_TAG }}
+          INPUT_PUSH_SNAPSHOT: ${{ steps.inputs-and-secrets.outputs.PUSH_SNAPSHOT }}
 
       - name: Define backend test command
         id: test-backend-command
@@ -460,7 +503,11 @@ jobs:
               echo "pushToDockerHub=true" >> $GITHUB_OUTPUT
               echo "managerDockerImage=openremote/manager:$FIRST_MANAGER_TAG" >> $GITHUB_OUTPUT
             else
-              command="docker build --push --build-arg GIT_COMMIT=$commitSha --platform linux/amd64,linux/aarch64 -t ${{ steps.inputs-and-secrets.outputs.OR_AWS_DEVELOPERS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/openremote/manager:SNAPSHOT-$commitShaShort $buildPath && docker build --build-arg GIT_COMMIT=$commitSha --platform ${PLATFORM:-linux/amd64} --load -t openremote/manager:$commitShaShort $buildPath"
+              if [ "$PUSH_SNAPSHOT" == "true" ]; then
+                command="docker build --push --build-arg GIT_COMMIT=$commitSha --platform linux/amd64,linux/aarch64 -t ${{ steps.inputs-and-secrets.outputs.OR_AWS_DEVELOPERS_ACCOUNT_ID }}.dkr.ecr.eu-west-1.amazonaws.com/openremote/manager:SNAPSHOT-$commitShaShort $buildPath && docker build --build-arg GIT_COMMIT=$commitSha --platform ${PLATFORM:-linux/amd64} --load -t openremote/manager:$commitShaShort $buildPath"
+              else
+                command="docker build --build-arg GIT_COMMIT=$commitSha --platform ${PLATFORM:-linux/amd64} --load -t openremote/manager:$commitShaShort $buildPath && docker build --build-arg GIT_COMMIT=$commitSha --platform ${OTHER_PLATFORM:-linux/aarch64} -t openremote/manager:$commitShaShort $buildPath"
+              fi
               echo "managerDockerImage=openremote/manager:$commitShaShort" >> $GITHUB_OUTPUT
             fi
             echo "value=$command" >> $GITHUB_OUTPUT
@@ -471,6 +518,7 @@ jobs:
           FIRST_MANAGER_TAG: ${{ steps.ci-cd-output.outputs.firstDockerTag }}
           MANAGER_TAGS: ${{ steps.ci-cd-output.outputs.dockerTags }}
           DEPLOYMENTS: ${{ steps.deployments.outputs.value }}
+          PUSH_SNAPSHOT: ${{ steps.deployments.outputs.pushSnapshot }}
           TEST_UI_CMD: ${{ steps.test-ui-apps-command.outputs.value }}
 
       - name: Define maven publish command
@@ -478,12 +526,23 @@ jobs:
         if: ${{ steps.ci-cd-output.outputs.mavenTag != '' }}
         shell: bash
         run: |
-          command="./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository --no-parallel -PsigningKey=$MAVEN_SIGNING_KEY -PsigningPassword=$MAVEN_SIGNING_PASSWORD -PpublishUsername=$MAVEN_USERNAME -PpublishPassword=$MAVEN_PASSWORD"
+          command="./gradlew publishToSonatype --no-parallel -PsigningKey=$MAVEN_SIGNING_KEY -PsigningPassword=$MAVEN_SIGNING_PASSWORD -PpublishUsername=$MAVEN_USERNAME -PpublishPassword=$MAVEN_PASSWORD"
           echo "value=$command" >> $GITHUB_OUTPUT
         env:
           MAVEN_TAG: ${{ steps.ci-cd-output.outputs.mavenTag }}
           MAVEN_SIGNING_PASSWORD: ${{ steps.inputs-and-secrets.outputs._TEMP_MAVEN_SIGNING_PASSWORD }}
           MAVEN_SIGNING_KEY: ${{ steps.inputs-and-secrets.outputs._TEMP_MAVEN_SIGNING_KEY }}
+          MAVEN_USERNAME: ${{ steps.inputs-and-secrets.outputs._TEMP_MAVEN_USERNAME }}
+          MAVEN_PASSWORD: ${{ steps.inputs-and-secrets.outputs._TEMP_MAVEN_PASSWORD }}
+
+      - name: Define maven release command
+        id: maven-release-command
+        if: ${{ steps.ci-cd-output.outputs.mavenTag != '' }}
+        shell: bash
+        run: |
+          command="./gradlew findSonatypeStagingRepository closeAndReleaseSonatypeStagingRepository -PpublishUsername=$MAVEN_USERNAME -PpublishPassword=$MAVEN_PASSWORD"
+          echo "value=$command" >> $GITHUB_OUTPUT
+        env:
           MAVEN_USERNAME: ${{ steps.inputs-and-secrets.outputs._TEMP_MAVEN_USERNAME }}
           MAVEN_PASSWORD: ${{ steps.inputs-and-secrets.outputs._TEMP_MAVEN_PASSWORD }}
 
@@ -534,14 +593,14 @@ jobs:
           password: ${{ steps.inputs-and-secrets.outputs._TEMP_DOCKERHUB_PASSWORD }}
 
       - name: Configure AWS Credentials
-        if: ${{ steps.manager-docker-command.outputs.pushToDockerHub != 'true' }}
+        if: ${{ steps.deployments.outputs.pushSnapshot == 'true' }}
         uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
         with:
           aws-region: eu-west-1
           role-to-assume: "arn:aws:iam::${{ steps.inputs-and-secrets.outputs.OR_AWS_DEVELOPERS_ACCOUNT_ID }}:role/${{ steps.inputs-and-secrets.outputs.OR_GH_AWS_ECR_PUSH_ROLE }}"
 
       - name: Login to private ECR
-        if: ${{ steps.manager-docker-command.outputs.pushToDockerHub != 'true' }}
+        if: ${{ steps.deployments.outputs.pushSnapshot == 'true' }}
         uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
 
       - name: set up QEMU
@@ -557,15 +616,6 @@ jobs:
         with:
           version: latest
           install: true
-
-      - name: Set up JDK 21 and gradle cache
-        id: java
-        if: ${{ steps.install-command.outputs.value != '' || steps.test-backend-command.outputs.value != '' }}
-        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4
-        with:
-          distribution: 'temurin'
-          java-version: '21'
-          cache: 'gradle'
 
       - name: Get yarn cache directory path
         id: yarn-cache-dir-path
@@ -600,6 +650,7 @@ jobs:
           echo 'Manager docker build command: ${{ steps.manager-docker-command.outputs.value }}'
           echo 'Manager docker image: ${{ steps.manager-docker-command.outputs.managerDockerImage }}'
           echo 'Maven publish command: ${{ steps.maven-publish-command.outputs.value }}'
+          echo 'Maven release command: ${{ steps.maven-release-command.outputs.value }}'
           echo 'Deployment docker build command: ${{ steps.deployment-docker-command.outputs.value }}'
           echo 'InstallDist command: ${{ steps.install-command.outputs.value }}'
           echo "Java version: $(java --version)"
@@ -650,6 +701,24 @@ jobs:
         env:
           VERSION: ${{ steps.get-version-details.outputs.version_with_qualifier }}
 
+      - name: Check for outdated translations
+        if: steps.is_main_repo.outputs.value == 'true'
+        run: |
+          set -e
+
+          # Run the tests
+          ./gradlew -p ui/app/shared processTranslations --no-parallel
+
+          out=$(git status --porcelain | grep "ui/app/shared/locales" || true)
+          if [[ -z "$out" ]]; then
+              echo "✅ No pipeline changes detected."
+          else
+              echo "❌ Pipeline files have changed. Please run './gradlew -p ui/app/shared processTranslations --no-parallel'"
+              echo "$out"
+              exit 1
+          fi
+        timeout-minutes: 20
+
       - name: Run backend tests
         id: run-backend-tests
         if: ${{ steps.test-backend-command.outputs.value != '' }}
@@ -678,6 +747,12 @@ jobs:
         with:
           name: backend-test-results
           path: test/build/reports/tests
+
+      - name: Archive coverage report
+        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
+        with:
+          name: coverage-report
+          path: test/build/reports/jacoco/test/html
 
       - name: Cleanup backend tests
         if: ${{ steps.test-backend-command.outputs.value != '' }}
@@ -721,13 +796,18 @@ jobs:
           INPUTS_AND_SECRETS: ${{ toJSON(steps.inputs-and-secrets.outputs) }}
         timeout-minutes: 20
 
+      - name: Run NPM publish dry run
+        if: steps.is_main_repo.outputs.value == 'true' && github.ref != 'refs/heads/master'
+        run: yarn workspaces foreach --all --no-private --topological npm publish --dry-run
+        timeout-minutes: 20
+
       - name: Run install playwright browser(s)
         if: (steps.test-ui-components-command.outputs.value != '' || steps.test-ui-apps-command.outputs.value != '') && steps.is_main_repo.outputs.value == 'true'
         run: npx playwright install --with-deps chromium
         timeout-minutes: 20
 
       - name: Run UI component tests
-        if: steps.test-ui-components-command.outputs.value != ''
+        if: steps.test-ui-components-command.outputs.value != '' && steps.is_main_repo.outputs.value == 'true'
         run: ${{ steps.test-ui-components-command.outputs.value }}
         timeout-minutes: 20
         # continue-on-error: true
@@ -778,7 +858,7 @@ jobs:
 
       - name: Scan manager docker image
         if: steps.manager-docker-command.outputs.pushToDockerHub == 'true'
-        uses: anchore/scan-action@2c901ab7378897c01b8efaa2d0c9bf519cc64b9e # v6.2.0
+        uses: anchore/scan-action@3c9a191a0fbab285ca6b8530b5de5a642cba332f # v7.2.2
         id: manager-anchore-scan
         with:
           image: ${{ steps.manager-docker-command.outputs.managerDockerImage }}
@@ -789,7 +869,7 @@ jobs:
         if: |
           !cancelled() &&
           steps.manager-docker-command.outputs.pushToDockerHub == 'true'
-        uses: github/codeql-action/upload-sarif@e488e3c8239c26bf8e6704904a8cb59be658d450 # v3
+        uses: github/codeql-action/upload-sarif@c8e3174949dcd2ceb71718aeaa53fee4dc9052f2 # v4.31.7
         with:
           sarif_file: ${{ steps.manager-anchore-scan.outputs.sarif }}
 
@@ -820,6 +900,12 @@ jobs:
         if: steps.deployment-docker-command.outputs.value != ''
         run: |
           ${{ steps.deployment-docker-command.outputs.value }}
+
+      - name: Run maven release command
+        if: |
+          steps.maven-release-command.outputs.value != ''
+        run: |
+          ${{ steps.maven-release-command.outputs.value }}
 
       - name: Do deployments
         if: steps.deployments.outputs.value != ''
